### ISSUE TITLE
paradise doesn't compile with latest Scala 2.12.x

### ISSUE THREAD

**Issue by SethTisue** [scalamacros/paradise#78]
in the community build run https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/309/consoleFull we see:

``` text
[macro-paradise] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/macro-paradise-21ffe7a7ba52c5fa52f67b89b7e263d1bd2af480/plugin/src/main/scala/org/scalamacros/paradise/typechecker/Namers.scala:253: not found: value noEnterGetterSetter
[macro-paradise] [error]           if (noEnterGetterSetter(tree)) {
[macro-paradise] [error]               ^
[macro-paradise] [error] one error found
[macro-paradise] [error] (paradise/compile:compileIncremental) Compilation failed
```

I believe it's because of @adriaanm's commit https://github.com/scala/scala/commit/66a316a4acdb2584ef9d85f15b950f12c94d909c

in the context of the 2.12.x community build, macro paradise not compiling means Play and Shapeless can't be built. (and then some further projects depend on Shapeless, of course.)

**Comment by xeno-by** [comment]
How urgent is this? I can look into it this week, but probably not today or tomorrow.

**Comment by SethTisue** [comment]
it's not super urgent. if you could look at this before we build 2.12.0-M4, that would be best. the earliest we might build M4 is Mon Feb 8.

**Comment by adriaanm** [comment]
[re: ... Feb 8...]  it'll be at least a couple days after that -- the impl class work still needs to be turned into a PR, and so does my SAM-always-one one

**Comment by xeno-by** [comment]
Where do you guys publish nightly builds of 2.12.x? I just cloned and compiler the 2.12.x branch of paradise and everything worked just fine.

My `sbt update` says `[info] 'compiler-interface' not yet compiled for Scala 2.12.0-20150526-104104-7b224c57c2. Compiling...`, which kinda hints at the fact that something is stale.

**Comment by dwijnand** [comment]
@xeno-by Try this: https://github.com/scala/scala#tips--tricks

**Comment by xeno-by** [comment]
Neat. What should I write instead of <...> in `set scalaVersion := "<milestone>-<sha7>-SNAPSHOT"`?

**Comment by dwijnand** [comment]
Try `2.12.0-f48692d-SNAPSHOT`

**Comment by xeno-by** [comment]
@SethTisue could you try again? Looks like I have forgotten to cherry-pick some fixups from the 2.12.0-M3 branch to 2.12.x.

**Comment by milessabin** [comment]
What's the current status of this?

**Comment by SethTisue** [comment]
new community build run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/310/consoleFull (is 404 at the moment, while the Jenkins queue clears)

**Comment by SethTisue** [comment]
yay, fixed. thanks @xeno-by

**Comment by milessabin** [comment]
Thanks :-)
